### PR TITLE
[WIP] Rehaul v2

### PR DESCRIPTION
**Pull request by sirocchj**

### CODE REVIEW

**Review by barambani — APPROVED** [review]

**Comment by sirocchj** [comment]
This will need one/two follow-ups but I think we better start merging back in

**Review by barambani — APPROVED** [review]

**Comment by barambani** [comment]
🎉

**Comment by sirocchj** [comment]
@barambani not sure why snyk now reports again two issues from the aws sdk that previously did not report… anyhow… happy to merge?

**Comment by barambani** [comment]
I'm not sure why Snyk didn't fail on this week's PRs. It could be a glitch. I actually was expecting it to keep failing as we still depend on an affected version. Anyway let's merge, yes.

**Pull request merged**
