### PR TITLE
Abstract tamer job introduced, rest module stub

### PR DESCRIPTION
**Pull request by pshirshov**

### CODE REVIEW

**Comment by gurghet** [comment]
I presume the job abstraction is to use it with the rest module as well

**Comment by pshirshov** [comment]
> I presume the job abstraction is to use it with the rest module as well

Yup, I've reused it in doobie module (see the other PR)

**Review by barambani — APPROVED** [review]

**Comment by barambani** [comment]
It probably just needs `fmt`

**Comment by barambani** [comment]
Same as https://github.com/laserdisc-io/tamer/pull/261#issuecomment-791582028

**Comment by sirocchj** [comment]
So this:
1. needs scalafmt and
2. needs to solve the security issues

On 2, the Netty ones should be solvable by forcing the later patch version, not sure how to go about the other one though.

Am I missing something?

**Pull request closed without merging**
