### PR TITLE
db#fetch converted into Job

### PR DESCRIPTION
**Pull request by pshirshov**

### CODE REVIEW

**Comment by barambani** [comment]
oh, there is also [this](https://snyk.io/vuln/SNYK-JAVA-COMBEUST-174815).

Screenshot 2021-03-05 at 17 52 44

do we have any way to mitigate it ?

**Comment by pshirshov** [comment]
@barambani dunno, this looks like a triple false positive for me. First of all, it comes from an artifact in the test scope.

Then jcommander is present on central: https://search.maven.org/search?q=jcommander

Then, I don't see any http repo in this list: https://github.com/cbeust/testng/blob/69d9ed55533374449145a20207fa467ffb5660ee/build.gradle.kts#L60

**Comment by barambani** [comment]
There are 7 of them all from `org.asynchttpclient:async-http-client@2.12.2`. It seems to use a version of netty from last October (`4.1.53.Final`). All of them apart the jcommander one seem resolved at the current version of netty that's pretty fresh (4.1.59.Final from 25 days ago). The jcommander comes from a `netty-reactive-streams` from Nov 19, 2019 though. One can be a false positive, but it seems that `org.asynchttpclient async-http-client` is not super up to date. I will see next week if I can add an exception. I would like to keep the check enabled.

**Comment by barambani** [comment]
Netty example:

Screenshot 2021-03-05 at 19 13 59

**Pull request closed without merging**
